// frontend-vue/src/components/ClimateList.vue
<template>
  <Dashboard :records="records" />

  <Alerts :records="records" />

  <ClimateForm
    :selected-record="selectedRecord"
    @record-created="handleCreate"
    @record-updated="handleUpdate"
  />

  <div class="card shadow">
    <div class="card-header bg-dark text-white fw-bold">
      📋 Registros Climáticos ({{ filteredRecords.length }})
    </div>

    <div class="card-body table-responsive">
      <input
       v-model="searchText"
       type="text"
       class="form-control shadow-sm mb-3"
       placeholder="🔍 Buscar registros por ciudad..."
       />

      <table class="table table-striped table-hover align-middle">
        <thead class="table-dark">
          <tr>
            <th>ID</th>
            <th>Ciudad</th>
            <th>Temperatura</th>
            <th>Humedad</th>
            <th>Presión</th>
            <th>Fecha</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          <tr v-if="filteredRecords.length === 0">
         <td colspan="7" class="text-center text-muted py-4">
         📭 No existen registros climáticos.
          </td>
         </tr>

          <tr
          v-for="record in filteredRecords"
          :key="record.id"
          v-else
           >
            <td>{{ record.id }}</td>
            <td class="fw-bold">📍 {{ record.city }}</td>
            <td><span :class="`badge ${getTemperatureBadge(record.temperature)}`">{{ record.temperature }} °C</span></td>
            <td><span :class="`badge ${getHumidityBadge(record.humidity)}`">{{ record.humidity }} %</span></td>
            <td>{{ record.pressure }} hPa</td>
            <td>{{ formatDate(record.date) }}</td>
            <td>
              <button
                class="btn btn-warning btn-sm me-2"
                @click="handleEdit(record)"
              >
                ✏️ Editar
              </button>

              <button
                class="btn btn-danger btn-sm"
                @click="handleDelete(record.id)"
              >
                🗑 Eliminar
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import type { ClimateRecord } from '../models/ClimateRecord'
import {
  getRecords,
  createRecord,
  updateRecord,
  deleteRecord,
} from '../services/climateService'
import Alerts from './Alerts.vue'
import Dashboard from './Dashboard.vue'
import ClimateForm from './ClimateForm.vue'

const records = ref<ClimateRecord[]>([])
const selectedRecord = ref<ClimateRecord | null>(null)
const searchText = ref('')

const filteredRecords = computed(() => {
  return [...records.value]
    .filter((record) =>
      record.city.toLowerCase().includes(searchText.value.toLowerCase())
    )
    .sort(
      (a, b) =>
        new Date(b.date).getTime() - new Date(a.date).getTime()
    )
})

onMounted(() => {
  loadRecords()
})

async function loadRecords() {
  try {
    records.value = await getRecords()
  } catch (error) {
    console.error(error)
  }
}

async function handleCreate(record: Omit<ClimateRecord, 'id'>) {
  try {
    await createRecord(record)
    await loadRecords()
  } catch (error) {
    console.error(error)
  }
}

function handleEdit(record: ClimateRecord) {
  selectedRecord.value = { ...record }
}

async function handleUpdate(record: Omit<ClimateRecord, 'id'>) {
  if (!selectedRecord.value) return

  try {
    await updateRecord(selectedRecord.value.id, record)
    selectedRecord.value = null
    await loadRecords()
  } catch (error) {
    console.error(error)
  }
}

async function handleDelete(id: number) {
  const confirmDelete = confirm('¿Seguro que deseas eliminar este registro?')

  if (!confirmDelete) return

  try {
    await deleteRecord(id)
    await loadRecords()
  } catch (error) {
    console.error(error)
  }
}

function getTemperatureBadge(temp: number) {
  if (temp >= 40) return 'bg-danger'
  if (temp >= 30) return 'bg-warning text-dark'
  return 'bg-success'
}

function getHumidityBadge(humidity: number) {
  if (humidity >= 80) return 'bg-danger'
  if (humidity >= 60) return 'bg-warning text-dark'
  return 'bg-primary'
}

function formatDate(date: string) {
  return new Date(date).toLocaleString('es-PE', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}
</script>

// frontend-angular/src/app/components/climate-list/climate-list.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ClimateFormComponent } from '../climate-form/climate-form.component';
import { ChangeDetectorRef } from '@angular/core';
import { ClimateService } from '../../services/climate.service';
import { ClimateRecord } from '../../models/climate-record';
import { DashboardComponent } from '../dashboard/dashboard.component';
import { AlertsComponent } from '../alerts/alerts.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-climate-list',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    DashboardComponent,
    ClimateFormComponent,
    AlertsComponent
  ],
  templateUrl: './climate-list.component.html',
})
export class ClimateListComponent implements OnInit {
  private climateService = inject(ClimateService);
  private cdr = inject(ChangeDetectorRef);

  records: ClimateRecord[] = [];
  selectedRecord: ClimateRecord | null = null;
  searchText = '';

  get filteredRecords(): ClimateRecord[] {
    return this.records.filter(record =>
      record.city.toLowerCase().includes(this.searchText.toLowerCase())
    );
  }

  ngOnInit(): void {
    this.loadRecords();
  }

  loadRecords(): void {
  this.climateService.getAll().subscribe({
    next: (data) => {
      this.records = data;
      this.cdr.detectChanges();
    },
    error: (error) => {
      console.error('Error al cargar registros:', error);
    },
  });
}

createRecord(record: Omit<ClimateRecord, 'id'>): void {
    this.climateService.create(record).subscribe({
      next: () => {
        this.loadRecords(); // Recarga la tabla
        this.cdr.detectChanges();
      },
      error: (error) => {
        console.error('Error al crear registro:', error);
      },
    });
  }

  editRecord(record: ClimateRecord): void {
  this.selectedRecord = { ...record };
}

updateRecord(record: ClimateRecord): void {
  this.climateService.update(record.id, record).subscribe({
    next: () => {
      this.selectedRecord = null;
      this.loadRecords();
      this.cdr.detectChanges();
    },
    error: (error) => {
      console.error('Error al actualizar registro:', error);
    },
  });
}

  deleteRecord(id: number): void {
  const confirmDelete = confirm('¿Seguro que deseas eliminar este registro?');

  if (!confirmDelete) return;

  this.climateService.delete(id).subscribe({
    next: () => {
      this.records = this.records.filter(record => record.id !== id);
      this.cdr.detectChanges();
    },
    error: (error) => {
      console.error('Error al eliminar registro:', error);
    },
  });
}

}

<app-dashboard [records]="records"></app-dashboard>

<app-alerts [records]="records"></app-alerts>

<app-climate-form
  [selectedRecord]="selectedRecord"
  (recordCreated)="createRecord($event)"
  (recordUpdated)="updateRecord($event)">
</app-climate-form>


<div class="card shadow">
  <div class="card-header bg-dark text-white fw-bold">
    📋 Registros Climáticos
  </div>

  <div class="card-body table-responsive">
    <div class="mb-3">
  <input
    type="text"
    class="form-control"
    placeholder="🔍 Buscar ciudad..."
    [(ngModel)]="searchText"
  />
</div>
    <table class="table table-striped table-hover align-middle">
      <thead class="table-dark">
        <tr>
          <th>ID</th>
          <th>Ciudad</th>
          <th>Temperatura</th>
          <th>Humedad</th>
          <th>Presión</th>
          <th>Fecha</th>
          <th>Acciones</th>
        </tr>
      </thead>

      <tbody>
        <tr *ngFor="let record of filteredRecords">
          <td>{{ record.id }}</td>
          <td>{{ record.city }}</td>
          <td>{{ record.temperature }} °C</td>
          <td>{{ record.humidity }} %</td>
          <td>{{ record.pressure }} hPa</td>
          <td>{{ record.date | date:'dd/MM/yyyy HH:mm' }}</td>

          <td>

            <button
             type="button"
             class="btn btn-warning btn-sm me-2"
            (click)="editRecord(record)">
              Editar
            </button>

            <button
              type="button"
              class="btn btn-danger btn-sm"
              (click)="deleteRecord(record.id)">
              Eliminar
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
