// frontend-react/src/App.tsx
import { useState } from 'react';
import ClimateList from './components/ClimateList';
import Login from './components/Login';
import { isLoggedIn, logout } from './services/authService';

function App() {
  const [authenticated, setAuthenticated] = useState(isLoggedIn());

  function handleLogout() {
    logout();
    setAuthenticated(false);
  }

  if (!authenticated) {
    return <Login onLogin={() => setAuthenticated(true)} />;
  }

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 className="text-primary fw-bold">
            🌦 Sistema de Gestión Climática
          </h1>
          <p className="text-muted mb-0">
            Frontend React protegido con JWT
          </p>
        </div>

        <button className="btn btn-outline-danger" onClick={handleLogout}>
          Cerrar sesión
        </button>
      </div>

      <ClimateList />
    </div>
  );
}

export default App;

// frontend-vue/src/App.vue
<template>
  <Login v-if="!authenticated" @logged-in="handleLogin" />

  <div v-else class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h1 class="text-primary fw-bold">
          🌦 Sistema de Gestión Climática
        </h1>
        <p class="text-muted mb-0">
          Frontend Vue protegido con JWT
        </p>
      </div>

      <button class="btn btn-outline-danger" @click="handleLogout">
        Cerrar sesión
      </button>
    </div>

    <ClimateList />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

import ClimateList from './components/ClimateList.vue'
import Login from './components/Login.vue'
import { isLoggedIn, logout } from './services/authService'

const authenticated = ref(isLoggedIn())

function handleLogin() {
  authenticated.value = true
}

function handleLogout() {
  logout()
  authenticated.value = false
}
</script>
