// frontend-react/src/components/Dashboard.tsx
import type { ClimateRecord } from "../models/ClimateRecord";

interface DashboardProps {
  records: ClimateRecord[];
}

export default function Dashboard({ records }: DashboardProps) {
  const totalRecords = records.length;

  const averageTemperature =
    records.length === 0
      ? 0
      : records.reduce((sum, record) => sum + record.temperature, 0) /
        records.length;

  const averageHumidity =
    records.length === 0
      ? 0
      : records.reduce((sum, record) => sum + record.humidity, 0) /
        records.length;

  return (
    <div className="row mb-4">
      <div className="col-md-4 mb-3">
        <div className="card text-white bg-primary shadow">
          <div className="card-body text-center">
            <h5>📋 Total Registros</h5>
            <h2>{totalRecords}</h2>
          </div>
        </div>
      </div>

      <div className="col-md-4 mb-3">
        <div className="card text-white bg-success shadow">
          <div className="card-body text-center">
            <h5>🌡 Temperatura Promedio</h5>
            <h2>{averageTemperature.toFixed(1)} °C</h2>
          </div>
        </div>
      </div>

      <div className="col-md-4 mb-3">
        <div className="card text-white bg-info shadow">
          <div className="card-body text-center">
            <h5>💧 Humedad Promedio</h5>
            <h2>{averageHumidity.toFixed(1)} %</h2>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-angular/src/app/components/dashboard/dashboard.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ClimateRecord } from '../../models/climate-record';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  @Input() records: ClimateRecord[] = [];

  get totalRecords(): number {
    return this.records.length;
  }

  get averageTemperature(): number {
    if (this.records.length === 0) return 0;

    const total = this.records.reduce(
      (sum, record) => sum + record.temperature,
      0
    );

    return total / this.records.length;
  }

  get averageHumidity(): number {
    if (this.records.length === 0) return 0;

    const total = this.records.reduce(
      (sum, record) => sum + record.humidity,
      0
    );

    return total / this.records.length;
  }
}
<div class="row mb-4">

  <div class="col-md-4 mb-3">
    <div class="card text-white bg-primary shadow">
      <div class="card-body text-center">

        <h5 class="card-title">
          📋 Total de Registros
        </h5>

        <h2>
          {{ totalRecords }}
        </h2>

      </div>
    </div>
  </div>

  <div class="col-md-4 mb-3">
    <div class="card text-white bg-success shadow">
      <div class="card-body text-center">

        <h5 class="card-title">
          🌡 Temperatura Promedio
        </h5>

        <h2>
          {{ averageTemperature | number:'1.1-1' }} °C
        </h2>

      </div>
    </div>
  </div>

  <div class="col-md-4 mb-3">
    <div class="card text-white bg-info shadow">
      <div class="card-body text-center">

        <h5 class="card-title">
          💧 Humedad Promedio
        </h5>

        <h2>
          {{ averageHumidity | number:'1.1-1' }} %
        </h2>

      </div>
    </div>
  </div>

</div>
