// frontend-vue/src/components/Alerts.vue
<template>
  <div class="card shadow mb-4">
    <div class="card-header bg-dark text-white fw-bold">
      ⚠ Alertas Climáticas
    </div>

    <div class="card-body">
      <div v-if="alerts.length === 0" class="alert alert-success mb-0">
        ✅ No existen alertas climáticas.
      </div>

      <div
        v-for="(alert, index) in alerts"
        v-else
        :key="index"
        :class="`alert alert-${alert.type} mb-2`"
      >
        {{ alert.message }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ClimateRecord } from '../models/ClimateRecord'

const props = defineProps<{
  records: ClimateRecord[]
}>()

const alerts = computed(() => {
  const result: {
    message: string
    type: 'danger' | 'warning' | 'info'
  }[] = []

  props.records.forEach((record) => {
    if (record.temperature >= 40) {
      result.push({
        message: `🔥 Temperatura muy alta en ${record.city}: ${record.temperature} °C`,
        type: 'danger',
      })
    }

    if (record.temperature <= 10) {
      result.push({
        message: `❄ Temperatura muy baja en ${record.city}: ${record.temperature} °C`,
        type: 'info',
      })
    }

    if (record.humidity >= 80) {
      result.push({
        message: `💧 Humedad elevada en ${record.city}: ${record.humidity}%`,
        type: 'warning',
      })
    }
  })

  return result
})
</script>

// frontend-angular/src/app/components/alerts/alerts.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ClimateRecord } from '../../models/climate-record';

@Component({
  selector: 'app-alerts',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './alerts.component.html',
})
export class AlertsComponent {
  @Input() records: ClimateRecord[] = [];

  get alerts(): string[] {
    const alerts: string[] = [];

    this.records.forEach((record) => {
      if (record.temperature >= 35) {
        alerts.push(`🔥 Temperatura alta en ${record.city}: ${record.temperature} °C`);
      }

      if (record.temperature <= 10) {
        alerts.push(`❄️ Temperatura baja en ${record.city}: ${record.temperature} °C`);
      }

      if (record.humidity >= 90) {
        alerts.push(`💧 Humedad alta en ${record.city}: ${record.humidity}%`);
      }

      if (record.humidity <= 30) {
        alerts.push(`🏜️ Humedad baja en ${record.city}: ${record.humidity}%`);
      }
    });

    return alerts;
  }
}
<div class="card shadow mb-4">
  <div class="card-header bg-warning fw-bold">
    ⚠ Alertas Climáticas
  </div>

  <div class="card-body">
    @if (alerts.length === 0) {
      <div class="alert alert-success mb-0">
        ✅ No hay alertas climáticas.
      </div>
    } @else {
      @for (alert of alerts; track alert) {
        <div class="alert alert-danger">
          {{ alert }}
        </div>
      }
    }
  </div>
</div>
